// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adezjlfoufuhlmwpgrnz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZXpqbGZvdWZ1aGxtd3Bncm56Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTcwMjEsImV4cCI6MjA2MzY3MzAyMX0.wbcd45JQ2ejMzDvI8Fc1_lJMWfInGC0PIoeAYFyI1D8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);